# backend/prometheus.yml
global:
  scrape_interval:     15s    # jak często pobierać metryki
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'rezsport-backend'
    static_configs:
      - targets: ['localhost:4000']    # adres Twojej aplikacji
    metrics_path: '/metrics'
    scrape_interval: 5s               # krócej na czas developmentu
